version: '3'
services: 
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - 80:80
#    volumes:
 #     - "./default.conf:/etc/nginx/conf.d/default.conf"


