# version: '3.8'

services: 
  nginx:
    container_name: nginx
    volumes:
       - ./web:/var/www/html/
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "80:80"
    depends_on:
     - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress
    volumes:
      - ./web:/var/www/html
    expose:
      - "9000"

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always




