version: '3'
services: 
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - 443:443
#    volumes:
 #     - "./default.conf:/etc/nginx/conf.d/default.conf"
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    



